# Generated by Django 2.1.5 on 2019-02-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_author_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='post',
        ),
        migrations.AddField(
            model_name='author',
            name='post',
            field=models.ManyToManyField(blank=True, null=True, to='blogs.Post'),
        ),
    ]
