# Generated by Django 2.1.5 on 2019-02-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190226_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ManyToManyField(blank=True, to='blogs.Author'),
        ),
    ]
