# Generated by Django 2.1.5 on 2019-02-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20190226_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='author',
            name='post',
            field=models.ManyToManyField(blank=True, to='blogs.Author'),
        ),
    ]
