# Generated by Django 2.1.5 on 2019-02-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20190226_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='post',
            field=models.ManyToManyField(blank=True, to='blogs.Post'),
        ),
    ]
