# Generated by Django 2.1.5 on 2019-02-26 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20190226_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='post',
        ),
    ]
