# Generated by Django 2.1.5 on 2019-02-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_remove_author_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='post',
            field=models.ManyToManyField(blank=True, to='blogs.Post'),
        ),
    ]
