# Generated by Django 2.1.5 on 2019-02-26 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_author_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='middle_name',
        ),
    ]
