# Generated by Django 2.1.5 on 2019-02-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_remove_author_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='post',
            field=models.ManyToManyField(to='blogs.Post'),
        ),
    ]
