# Generated by Django 2.1.5 on 2019-02-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_post_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publishDate',
            field=models.DateField(null=True),
        ),
    ]
