# Generated by Django 2.1.5 on 2019-02-26 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_post_publishdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publishDate',
            new_name='publish_date',
        ),
    ]
